import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.scss']
})
export class NewComponent implements OnInit

 

{
  biendem:number=1;
  bienbtn:number;
DSTinTuc:any=[{id:"1",content2:"Bill Denbrough là thủ lĩnh nhóm Losers' Club trong cuộc chiến chống lại It. Bill luôn là người thúc giục nhóm bạn cùng chung sức đánh bại sinh vật ma quái này một lần và mãi mãi. Động lực khiến cậu kiên trì là vì nỗi đau sau cái chết của cậu em trai Georgie. Hơn ai hết, It là kẻ Bill căm thù nhất vì nó đã cướp đi người em trai câu thương yêu. Trong phần đầu tiên, It đã xuất hiện với hình dạng của Georgie trong lần chạm trán với Bill.Bên cạnh đó, Bill còn mắc chứng nói lắp và thường xuyên bị trêu chọc đến khổ sở vì tật này. Bệnh nói lắp khiến Bill thành đối tượng bị bắt nạt và trở nên tự ti. Mỗi khi căng thẳng, căn bệnh càng hành hạ làm Bill không thể thốt ra một câu hoàn chỉnh.Không có gì chắc chắn rằng các diễn biến của It Chapter Two sẽ giống như tiểu thuyết, nhưng trong trailer cuối của bộ phim các khán giả có thể thấy Bill tuyệt vọng vùng vẫy khi thấy một cậu bé khác bị Pennywise, tấn công. Có thể thấy, nỗi sợ không thể bảo vệ được mọi người của Bill vẫn được các nhà làm phim giữ nguyên trong phần hai này.",name:"Bạn còn nhớ hay đã quên nhóm bạn Losers' Club đối đầu với hề Pennywise?",content:"27 năm sau, liệu họ có đủ 'mạnh' diệt It một lần và mãi mãi?",Img:"assets/img_tintuc-new/new1.jpg" },
{id:"2",content2:"Sau thành công của 2 phần Spider-Man mà gần đây nhất là doanh thu hơn 1 tỷ USD của Spider-Man: Far From Home (2019), Disney muốn góp phân nửa số vốn và dĩ nhiên là chia đôi lợi nhuận. Những điều khoản này cũng áp dụng cho các tác phẩm khác đi cùng với Nhện như Venom, Morbius,… Sony không chấp nhận và rồi Marvel quyết định “đá” Spider-Man ra khỏi MCU cũng như rút Kevin Feige về với lí do tập trung vào các dự án khác như X-Men, Fantastic Four,…Nhìn vào hợp đồng của 2 hãng, chúng ta dễ thấy rằng Marvel đang “làm thuê” cho Sony, được trả thù lao và hưởng 5% doanh thu phim. Họ không phải bỏ ra bất kỳ chi phí hay chịu rủi ro nào nếu phim thất bại tại phòng vé. Không những thế, Marvel còn được hưởng toàn bộ số tiền khổng lồ từ các tác phẩm Avengers có sự góp mặt của Spider-Man như Captain America: Civil War (2016), Avengers: Infinity War (2018) và Avengers: Endgame (2019).Nếu nói rằng nhờ MCU mà phim riêng của Spider-Man trở nên ăn khách hơn thì chính nhân vật của Tom Holland cũng đang làm điều ngược lại với các phần phim team-up (kết hợp nhiều nhân vật). Con số 175 triệu USD cho các sản phẩm đồ chơi cũng không hề quá đáng cho Marvel khi Nhện đã mang về hơn 200 triệu USD lợi nhuận mỗi năm từ thị trường này. Việc đòi “ăn đồng chia đủ” dường như là một nước đi khá tham lam của Marvel khi Sony mới là công ty nắm trọn bản quyền Spider-Man.",name:"Sony và Disney 'chia tay đòi Spider-Man' - Ai là người chịu thiệt?",content:"Cuối cùng thì đại diện Sony cũng chính thức lên tiếng và xác nhận Spider-Man không còn ở MCU (Vũ trụ Điện ảnh Marvel) nữa. Nhưng ai là người chịu thiệt thòi hơn trong màn “chia tay thế kỉ” này?",Img:"assets/img_tintuc-new/new2.jpg" },
{id:"3",content2:"Câu chuyện phim xoay quanh 4 cô gái Mia (Sophie Nélisse), Sasha (Corinne Foxx), Nicole (Sistine Stallone) và Alexa (Brianne Tju) quyết định lặn xuống biển để khám phá một thành cổ của người Maya dưới đáy đại dương. Khi vào đến bên trong, cổng thành bỗng sụp đổ khiến họ phải nhanh chóng tìm cách thoát thân trong những đường hầm mê cung và các hang động kỳ quái trước khi cạn sạch dưỡng khí. Cơn ác mộng lạc lối dưới biển sâu càng trở nên kinh khủng hơn khi các cô gái phát hiện ra thành phố dưới biển này chính là nơi cư ngụ của loài cá mập trắng khổng lồ khát máu. Liệu tất cả bọn họ đều sống sót, hay sẽ có người phải bỏ mạng bởi sự tò mò của chính mình?Sau cuối tuần đầu tiên khởi chiếu ở Bắc Mỹ, Hung Thần Đại Dương: Thảm Sát đã thu về những đánh giá tích cực từ các trang phê bình. So sánh với những siêu phẩm trước đây, tạp chí Chicago Suntimes dành lời khen ngợi phim: “Sau 44 năm kể từ Hàm Cá Mập, đây là bộ phim về đề tài cá mập tiếp theo khiến tim tôi muốn vỡ ra vì hồi hộp.”Trong khi đó, tạp chí Variety nổi tiếng nhận xét phim “ghê sợ và rùng rợn hơn cả The Meg”. 95% cảnh phim được quay hoàn toàn dưới nước, mang lại hiệu ứng hình ảnh chân thật đáng kinh ngạc, hứa hẹn sẽ khiến khán giả hoàn toàn đắm chìm vào không gian đại dương đáng sợ mà bộ phim mang lại",name:"Quái vật biển sâu trở lại trong Hung Thần Đại Dương: Thảm Sát",content:"Cá sấu vừa xong thì giờ đến cá mập tấn công phòng vé..",Img:"assets/img_tintuc-new/new3.jpg" },
{id:"4",content2:"Địa Đạo Cá Sấu Tử Thần bắt đầu với cảnh tượng cơn siêu bão ập vào vùng Florida. Nhưng thảm họa thiên nhiên không phải kẻ thù duy nhất mà các nhân vật của bộ phim phải đối đầu. Ẩn náu trong làn nước là những con cá sấu hung tợn chỉ chực chờ xé xác mọi sinh vật sống. Đặt một tác phẩm đề tài quái vật săn mồi trong bối cảnh thảm họa thiên nhiên là ý tưởng độc đáo mà đơn giản tới nỗi chính đạo diễn của phim cũng không ngờ rằng chưa ai từng thực hiện nó trước đây. Bằng việc khéo léo kết hợp hai thể loại phổ biến trong dòng phim kinh dị, tác phẩm sẽ chạm tới nỗi sợ hãi sâu thẳm trong bản năng con người.Cá sấu là loài động vật cổ xưa với hàm răng sắc nhọn, có khả năng nghiền nát con mồi, còn cơn cuồng phong bão táp cũng dễ dàng nuốt chửng con người. Cuộc chiến giành giật sự sống với hai thế lực khủng khiếp của thiên nhiên trở nên căng thẳng và kịch tính gấp bội.Trong suốt thời lượng phim, bộ đôi biên kịch Michael và Shawn Rasmussen khiến khán giả không kịp thở với liên tiếp những tình huống bị săn đuổi thót tim. Hai cha con Hailey liên tục đổ máu và bầm dập trong từng lượt chạm trán với lũ săn mồi khát máu. Mỗi lần Hailey tìm đường thoát thân khỏi tầng hầm địa ngục là một lần người xem thấp thỏm nhưng không thể rời mắt khỏi màn ảnh.",name:"3 lý do khiến bạn khó lòng bỏ qua siêu phẩm kinh dị, giật gân Địa Đạo Cá Sấu Tử Thần",content:"Với sự kết hợp giữa thảm hoạ và sức mạnh của thiên nhiên, phim sẽ khiến ban phải đặt vé ra rạp ngay đấy.",Img:"assets/img_tintuc-new/new4.jpg" },
{id:"5",content2:"Trở lại với bộ phim điện ảnh thứ 20 trong loạt phim, Thám Tử Lừng Danh Conan: Cơn Ác Mộng Đen Tối đánh dấu sự trở lại của Tổ chức Áo Đen. Nội dung phim xoay quanh Curacao, người đã đánh cắp danh sách các điệp viên MI6, BND, CSIS, FBI và CIA bí mật làm việc trong Tổ chức Áo Đen. Mọi nỗ lực tiêu diệt tổ chức đen tối này từ phía cảnh sát sẽ bị chấm dứt nếu trên danh sách này đến tay Gin.May thay, trong quá trình tẩu thoát, Curacao đã gặp tai nạn khiến cho cô bị mất trí nhớ. Hôm sau, Conan và đội thám tử nhí bắt gặp Curacao và quyết định sẽ giúp cô lấy lại trí nhớ của mình. Tuy nhiên, Tổ chức Áo Đen sẽ không dễ dàng bỏ qua danh sách quan trọng đó và loại bỏ những tên “chuột” đang trà trộn trong tổ chức. Lại một lần nữa, Conan bị lôi vào cuộc chiến với Tổ chức nguy hiểm, liệu số phận của cậu sẽ ra sao khi đối đầu với những tên trùm tội phạm?Thám Tử Lừng Danh Conan: Cơn Ác Mộng Đen Tối, bộ phim mang các nhân vật bí ẩn bậc nhất bộ truyện lên màn ảnh rộng cùng cốt truyện được đánh giá xuất sắc nhất trong các tập phim điện ảnh, đã dễ dàng chinh phục được trái tim khán giả toàn cầu với doanh thu lên đến 6,33 tỷ Yên. Phần phim thứ 20 đã đánh dấu cột mốc kỷ lục về doanh thu so với những bộ phim đi trước khi con số nhảy vọt lên đến gần 2 tỷ Yên. Những cảnh hành động trong phim được đặc biệt đầu tư với kỹ xảo điện ảnh mãn nhãn ngoài sức tưởng tượng. Đây chắc hẳn là một phần phim mà người hâm mộ Conan khó lòng bỏ qua.",name:"Conan và những phần phim gây sốt trên màn ảnh rộng Việt Nam",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new5.jpg" },
{id:"6",content2:"Sau khi chuyển công tác ra đảo Quý, Hoàng (Huyme) phải tiếp quản một lớp học đặc biệt gồm 5 học trò. Mỗi em đều khác nhau từ độ tuổi, tính cách cho đến những rắc rối mang lại cho thầy Hoàng.Cu là một cậu bé lầm lì, ít nói, hay khiến Hoàng khó chịu vì thường xuyên đi học muộn. Bù lại, cậu bé thực sự là một tài năng âm nhạc và sở hữu giọng hát thiên bẩm, điều tạo ra sợi dây liên kết giữa Cu và thầy Hoàng. Đảm nhận vai Cu là Nguyễn Minh Chiến - một tài năng âm nhạc thực sự ngoài đời với danh hiệu Á quân Giọng Hát Việt Nhí 2018. Theo đạo diễn Đức Thịnh, dù lần đầu đóng phim điện ảnh nhưng Minh Chiến sẽ mang đến rất nhiều cảm xúc cho khán giả nhờ lối diễn chân thật, tự nhiên của mình.So với Cu là học sinh ý thức kém, thì 4 học trò còn lại đều được thầy Hoàng ưu ái giao cho một chức vụ đặc biệt trong lớp. Ốc (Mai Cát Vi) là một cô bé lớp trưởng lém lỉnh, hay tỏ ra hiểu biết, và đặc biệt “ham chức quyền”, lúc nào cũng muốn đảm nhận hết mọi chức vụ trong lớp với lý do các bạn còn lại không đủ tư cách. Hến (Ngân Chi) thì lại là học trò ồn ào nhất lớp với tật mít ướt khiến thầy Hoàng phát cáu vì nhức đầu. Bù lại, Hến vẽ rất đẹp và chỉ thích vẽ thầy giáo. Hai mảnh ghép còn lại của lớp học là Tôm (Duy Sinh) và Sò (Bảo Phúc) cũng là những nhân tố mang đến không ít phiền toái cho thầy Hoàng. Tôm là học trò “đứng đầu” lớp trong nhiều lĩnh vực: ở dơ nhất vì không bao giờ chịu đánh răng, học kém nhất vì không biết làm toán nhưng lại đá banh cừ nhất. Trong khi đó, Sò là chuyên gia làm gián đoạn các buổi học vì hay ị đùn bất chấp thời điểm, khiến thầy Hoàng phải kiêm luôn công tác “bảo mẫu” xử lý hậu quả cho cậu bé. So với các bạn diễn nhí còn lại, cả Duy Sinh và Bảo Phúc là hai gương mặt “mới toanh” của điện ảnh Việt, hứa hẹn mang đến một làn gió mới cho khán giả.",name:"Khám phá tính cách đáng yêu của 5 học trò nhí trong Anh Thầy Ngôi Sao",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new6.jpg" },
{id:"7",content2:"Gợi nhắc đến Call Me by Your Name và Love, Simon, bộ phim Thưa Mẹ Con Đi cũng đưa hai chàng trai về vùng nông thôn yên ả. Văn (Lãnh Thanh) và Ian (Võ Điền Gia Huy) từ Mỹ trở về quê hương Việt Nam. Phông nền đồng quê dung dị nhưng nên thơ làm chuyện tình giữa hai chàng trai càng trở nên đẹp và lôi cuốn.Trong Love, Simon, có một câu thoại nội tâm rất đáng giá của nhân vật Simon: 'Tại sao người đồng tính phải come out?, cậu cho đó là điều “không công bằng. Và đó cũng là tư tưởng xuyên suốt Thưa Mẹ Con Đi'. Tác phẩm không cố lên gân hay quá bi lụy như những tác phẩm khác cùng đề tài. Ngược lại, bộ phim lựa chọn lối kể chuyện nhẹ nhàng hơn, xây dựng tâm lý nhân vật gần gũi với đời sống, nhưng cũng không kém phần tinh tế, sâu sắc.Nam chính Lãnh Thanh có ấn tượng mạnh mẽ với vai diễn lần này của mình: “Khi làm việc với ê-kíp về hình dung và không khí của phim, tôi được gợi ý tìm xem Call Me by Your Name bởi sự tương đồng về một câu chuyện nhẹ nhàng và dung dị. Thường mọi người sẽ nghĩ những câu chuyện gai góc, trái ngang mới khó nhưng với tôi, càng đơn giản lại càng đòi hỏi đầu tư nhiều cảm xúc.”",name:"Thưa Mẹ Con Đi giản dị nhưng lôi cuốn và còn gợi nhắc cả Call Me by Your,Name và Love, Simon",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new7.jpg" },
{id:"8",content2:"Là một nhân tố trong cuộc “đổ bộ” của phim Việt Nam trong tháng 8 này, Cậu Chủ Ma Cà Rồng tuy không sở hữu những ngôi sao phòng vé nhưng lại có nội dung khác biệt: lần đầu tiên, Ma cà rồng trở thành chủ đề khai thác trong phim điện ảnh Việt Nam.Teaser đầu tiên ra mắt trước đó đã hé lộ cuộc tuyển chọn quản gia gắt gao cho cậu chủ Ma cà rồng thần bí với sự tham gia của 5 cô gái trẻ đẹp nhưng đầy toan tính. Không khí phim vừa thần bí, vừa sang trọng lại vừa có mùi kịch tính của phim… “cung đấu” khiến khán giả tò mò. Đặc biệt, sự góp mặt của Nhật Hạ - sao nhí từng gây ấn tượng với series Gia Đình Phép Thuật và Mùi Ngò Gai cách đây hơn mười năm - cùng những diễn viên mới, nhan sắc bắt mắt, diễn xuất ổn chính là một điểm cộng đối với khán giả trẻ. Phân cảnh tái hiện tình tiết Nhật Hạ tát Angela Phương Trinh trong Mùi Ngò Gai 13 năm trước cũng rất thú vị, cho thấy sự đấu đá tranh giành của các cô gái trong phim sẽ rất kịch tính.Đáp lại sự tò mò của khán giả, 1990 Studio và đạo diễn Trần Nhân Kiên tiếp tục tung ra teaser thứ 2 nhưng không giống như những gì người ta có thể đoán trước. Tưởng đâu sẽ nối tiếp những đấu đá, tranh quyền đoạt lợi của 5 cô quản gia tập sự, ai ngờ Cậu Chủ Ma Cà Rồng lại bật mí một thế giới viễn tưởng rất đa dạng không chỉ có Ma cà rồng.",name:"Dù chưa ra mắt nhưng Cậu Chủ Ma Cà Rồng đã ủ mưu sản xuất phần tiếp theo??",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new8.jpg" },
{id:"9",content2:"Trailer chính thức của bộ phim mang tới cho khán giả cái nhìn rõ hơn về thảm họa khí ga nguy hiểm chết người mà Yong-nam (Jo Jung-seok) và Eui-ju (Im Yoona) đang mắc kẹt trong đó. Sau khi đưa cả gia đình lên nóc nhà và được trực thăng cứu hộ, vận rủi vẫn không tha cho Yong-nam khi chiếc trực thăng bị… quá tải, anh và cô bạn Eui-ju buộc phải ở lại chờ tới lượt tiếp theo.Trailer chính thức của bộ phim mang tới cho khán giả cái nhìn rõ hơn về thảm họa khí ga nguy hiểm chết người mà Yong-nam (Jo Jung-seok) và Eui-ju (Im Yoona) đang mắc kẹt trong đó. Sau khi đưa cả gia đình lên nóc nhà và được trực thăng cứu hộ, vận rủi vẫn không tha cho Yong-nam khi chiếc trực thăng bị… quá tải, anh và cô bạn Eui-ju buộc phải ở lại chờ tới lượt tiếp theo.Poster chính thức là đôi bạn đáng thương Yong-nam và Eui-ju với biểu cảm vừa thương vừa tội, đang trên đường… đu dây tới nơi an toàn. Khán giả sẽ được chứng kiến lần đầu tiên hợp tác vô cùng thú vị giữa Jo Jung-seok và nàng Yoona, cặp đôi sẽ cống hiến cho mọi người những tràng cười sảng khoái, những pha hành động toát mồ hôi hột và cả những thước phim vô cùng cảm động.",name:"Bom tấn gần 500,000 lượt xem chính thức đổ bộ phòng chiếu Việt Nam!",content:"Thảm hoạ khí ga Hàn Quốc liệu có làm mưa làm gió tại đất Việt?",Img:"assets/img_tintuc-new/new9.jpg" },
{id:"10",content2:"",name:"Mỹ nhân nào sẽ xuất hiện trong cuộc chiến của 2 anh 'đầu bóng loáng'?",content:"Những bộ phim trong 'vũ trụ' Fast & Furious thì không thể thiếu dàn chân dài tuyệt sắc đúng không nào?",Img:"assets/img_tintuc-new/new10.jpg" },
{id:"11",content2:"",name:"Trước Crawl, những hiểm hoạ cá sấu nào đáng xem nhất trên màn bạc điện ảnh?",content:"Chủ đề 'cá sấu ăn thịt' tuy đã quá quen thuộc với khán giả nhưng mỗi lần nhắc đến một trong những tác phẩm sau, hẳn ai cũng sẽ nổi da gà vì khoảnh khắc đáng sợ.",Img:"assets/img_tintuc-new/new11.jpg" },
{id:"12",content2:"",name:"100% cà chua tươi, Ký Sinh Trùng xứng đáng là bộ phim hay nhất của Bong Joon Ho",content:"Thắng giải Cành Cọ Vàng, tác phẩm nhận được tràng pháo tay dài tận 8 phút tại liên hoan phim quốc tế.",Img:"assets/img_tintuc-new/new12.jpg" },
{id:"13",content2:"",name:"Người tuyết Yeti chưa bao giờ dễ thương như thế trong Everest: Người Tuyết Bé Nhỏ",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new13.jpg" },
{id:"14",content2:"",name:"Godzilla và những điều bạn chưa biết (P2)",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new14.jpg" },
{id:"15",content2:"",name:" 4 cái tên nào sẽ mang đến bất ngờ cho khán giả 'nhí' vào nửa cuối năm 2019?",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new15.jpg" },
{id:"16",content2:"",name:"'Cô nàng cử tạ' sẽ làm gì để ngăn chặn nạn phát tán clip 'nóng' trong Phi Vụ Nữ Quyền?",content:"4sdfsdfasdfadfsdfsdfsdfsdfsdfasdfsdfasdfasd",Img:"assets/img_tintuc-new/new16.jpg" },
{id:"17",content2:"",name:"Godzilla và những điều bạn chưa biết (P1)",content:"Trước khi đại chiến diễn ra, cùng tìm hiểu mọi thông tin về Godzilla nào.",Img:"assets/img_tintuc-new/new17.jpg" },
{id:"18",content2:"",name:"Siêu anh hùng Shazam ra mắt trailer mới cực ‘lầy’ ",content:"Anh chàng “mặt phụ huynh, hồn học sinh” của nhà DC đã trở lại.",Img:"assets/img_tintuc-new/new18 .jpg" },

]
xemthem(){
    this.biendem++;
 console.log();
}

  constructor() { }

  ngOnInit() {
    this.dungbtn();
  }
dungbtn(){
  this.bienbtn=(this.DSTinTuc.length)/8;
  // console.log(this.bienbtn);
}


}

